name = "Poggy pack"
version = "1.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "EA9157252CB157A5A642DFD4FDB52698F6CA2BEE076BC6E09060A6057DD4A408"

[versions]
fabric = "0.13.3"
minecraft = "1.18.1"

[options]
acceptable-game-versions = ["1.18", "1.18.1", "1.18-rc3", "1.18-rc4"]
