name = "Poggy pack"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "746b917f0e3b0f0e815350b4da95196542633c509cc44ecdd0104863427dfa2e"

[versions]
forge = "40.0.0"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.2"]
