name = "Poggy pack"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5482bbe3418affe306797f39b2b1de5c20d18efc4ca2fb7c4fa886554bebe21c"

[versions]
forge = "40.0.0"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.2"]
