name = "Poggy pack"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "095eed0130356d850313567c5e4ff7df5603a3e9e3a5047709870454953dd23e"

[versions]
forge = "40.0.0"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.2"]
