name = "Adorn"
filename = "Adorn-3.5.0+1.18.2-forge.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/E6FUtRJh/versions/3.5.0-forge/Adorn-3.5.0%2B1.18.2-forge.jar"
hash-format = "sha1"
hash = "d3e6bd2f50ae3692e55f2cd217d7684c17aa3be4"

[update]
[update.modrinth]
mod-id = "E6FUtRJh"
version = "6knpxJnp"
