name = "AppleSkin"
filename = "appleskin-forge-mc1.18-2.4.0.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/EsAfCjCV/versions/forge-mc1.18-2.4.0/appleskin-forge-mc1.18-2.4.0.jar"
hash-format = "sha1"
hash = "36c297edae79cd9c33ce3cdb2230bc36fd9523f0"

[update]
[update.modrinth]
mod-id = "EsAfCjCV"
version = "eZRpJhZ6"
