name = "Applied Energistics 2 Wireless Terminals"
filename = "AE2WTLib-11.1.0.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/pNabrMMw/versions/11.1.0-forge/AE2WTLib-11.1.0.jar"
hash-format = "sha1"
hash = "6c1f4cf4498b8f3f52dd509a34c74a3f794e4245"

[update]
[update.modrinth]
mod-id = "pNabrMMw"
version = "UZ0HVbBd"
