name = "Botania"
filename = "Botania-1.18.2-433.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/pfjLUfGv/versions/1.18.2-433-forge/Botania-1.18.2-433.jar"
hash-format = "sha1"
hash = "b3d5a495ea65b89fa4fd8a155fe46de13eb97d74"

[update]
[update.modrinth]
mod-id = "pfjLUfGv"
version = "POoLUSdd"
