name = "More Axolotl Variants Mod"
filename = "mavm-mc1.18.2-forge-1.0.8b.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/zitu8weW/versions/v1.0.8b/mavm-mc1.18.2-forge-1.0.8b.jar"
hash-format = "sha1"
hash = "f26e8facbfc48ef55f3da260cec0fd27666248aa"

[update]
[update.modrinth]
mod-id = "zitu8weW"
version = "yrLMP7gR"
