name = "Mekanism Generators"
filename = "MekanismGenerators-1.18.2-10.2.3.463.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/OFVYKsAk/versions/10.2.3.463/MekanismGenerators-1.18.2-10.2.3.463.jar"
hash-format = "sha1"
hash = "0f2a50a950dd41a008a4528212385e0c7fe54e8a"

[update]
[update.modrinth]
mod-id = "OFVYKsAk"
version = "N51JaiWT"
