name = "Mekanism"
filename = "Mekanism-1.18.2-10.2.3.463.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/Ce6I4WUE/versions/10.2.3.463/Mekanism-1.18.2-10.2.3.463.jar"
hash-format = "sha1"
hash = "7e0bf877d5622d2eabb0ee28391cb87eac95fc90"

[update]
[update.modrinth]
mod-id = "Ce6I4WUE"
version = "g74zfl0m"
