name = "Not Enough Crashes"
filename = "notenoughcrashes-4.1.4+1.18.2-forge.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/yM94ont6/versions/4.1.4+1.18.2-forge/notenoughcrashes-4.1.4%2B1.18.2-forge.jar"
hash-format = "sha1"
hash = "c0b14165fe37f2005084dedb3a67c66e5c5246eb"

[update]
[update.modrinth]
mod-id = "yM94ont6"
version = "NZvd4cMK"
