name = "Smashing!"
filename = "smashing-forge-1.1.0+1.18.2.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/jVvDUhcz/versions/1.1.0/smashing-forge-1.1.0%2B1.18.2.jar"
hash-format = "sha1"
hash = "c111bcdc080ad3d8b833125428ce7b92a3bf237a"

[update]
[update.modrinth]
mod-id = "jVvDUhcz"
version = "Qeeqx9Eo"
