name = "spark"
filename = "spark-1.9.1-forge.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/l6YH9Als/versions/1.9.1-forge/spark-1.9.1-forge.jar"
hash-format = "sha1"
hash = "dcd813b20f51c5f6922b47d187a9ccaa485e4f50"

[update]
[update.modrinth]
mod-id = "l6YH9Als"
version = "6BEDTXhR"
