name = "Thermal Cultivation"
filename = "thermal_cultivation-1.18.2-1.6.1.9.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/5beJoehw/versions/1.6.1/thermal_cultivation-1.18.2-1.6.1.9.jar"
hash-format = "sha1"
hash = "116a5b77208155269bf3c4f682a032d4cb17607d"

[update]
[update.modrinth]
mod-id = "5beJoehw"
version = "VcaTnKYC"
